version: '3.0'

services:
  server:
    image: collov-server
    container_name: collov-server
    ports:
      - "4000:4000"
    # volumes: 
      # Persist the node_modules in a named vol. (only for development)
      # - node_modules:/usr/src/app/node_modules
      
    # For debugging only:
    # command: ["sleep", "40s"]

    command: ["node", "./serverBuild/server.js"]
    depends_on:
      - mongo-db
    
  mongo-db:
    image: mongo:3
    container_name: collov-mongo
    ports:
      - "27017:27017"
    volumes:
    # Persist the data that make up our DB between container starts/stops. 
      - collov-mongo-vol:/data/db

  nginx:
    image: nginx:alpine
    container_name: production_nginx
    ports:
      - "8080:8080"
    volumes:
      - "./build:/srv/www/static"
      - "./default.conf:/etc/nginx/nginx.conf"
    depends_on:
      - server

volumes:
  # node_modules:
  collov-mongo-vol: