import * as types from '../constants/actionTypes';

// 'status' indicates which list the applicant is on.
const addComments = (id: string, comments: string, name: string, status: string) => ({
  type: types.ADD_COMMENTS,
  payload: {
    id,
    comments,
    name,
    status,
  },
});

// Note that every newly created card gets the "Applied" status
// and goes into the Applied List. And we'll be using 
// a random ID generated by MongoDB to use as card's ID.
const addCard = (name: string, comments: string) => ({
  type: types.ADD_CARD,
  payload: {
    name,
    comments,
  }
});

const actions = {
  addComments,
  addCard,
};

export default actions;
