export const ADD_CARD = 'ADD_CARD';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const REMOVE_CURRENT_STATUS = 'REMOVE_CURRENT_STATUS';
export const GET_ALL_CARDS = 'REMOVE_CURRENT_STATUS';
export const SYNC_CARDS = 'SYNC_CARDS';
